version: '3.8'

services:
  pricehunt:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - ALIEXPRESS_API_KEY=${ALIEXPRESS_API_KEY}
      - ALIEXPRESS_AFFILIATE_ID=${ALIEXPRESS_AFFILIATE_ID}
      - ALIEXPRESS_APP_SECRET=${ALIEXPRESS_APP_SECRET}
      - PYTHONUNBUFFERED=1
    command: uvicorn app:app --host 0.0.0.0 --port 5001 --reload 