version: '3.8'

services:
  pricehunt:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ALIEXPRESS_API_KEY=${ALIEXPRESS_API_KEY}
      - ALIEXPRESS_AFFILIATE_ID=${ALIEXPRESS_AFFILIATE_ID}
      - ALIEXPRESS_APP_SECRET=${ALIEXPRESS_APP_SECRET}
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3 